spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shcooldb
    username: root
    password: rnrdj123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
