

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwtoauth
    username: root
    password: rnrdj123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 310073782191-1s4874uvqv0hgdoolg8vpl9ebc31nh1b.apps.googleusercontent.com
            client_secret: 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
            scope:
            - email
            - profile


          naver:
            client-id: hdBvlGRNNuu8vpdKNsVY
            client-secret: gph7GvFJ9o
            scope:
            - name
            - email
            - profile_image
            client-name: Naver # 클라이언트 네임은 구글 페이스북도 대문자로 시작하더라.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.




logging:
  level:
    com.example.security: debug