

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwtoauth
    username: root
    password: rnrdj123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true