spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mybatis
    username: root
    password: rnrdj123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true



mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml




