spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(MBo7pMY1HZC4CQrUvdIf5g==)
    url:  jdbc:mariadb://localhost:3306/studyApi
    password: ENC(CXHVxHeOOZ+EIXG4iXCFfpeZs5H7wlfy)
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      show_sql: true
  #############mail##########
  mail:
    host: smtp.gmail.com
    port: 587
    username: syseoz@gmail.com
    password: ENC(JxRE0UpO+asXY+oY3P1rZXb0HCO/H/0SBotzY0mCa5M=)
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
logging:
  level:
    com.demo.service: debug
    com.demo.security: debug



app:
  host: http://localhost:8080

token:
  expiration_time: 43200000
  secret: secret_s

## 프로퍼티 암호화 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor