spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url:  jdbc:mariadb://localhost:3306/studyApi
    password: rnrdj123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      show_sql: true
logging:
  level:
    com.demo.service: debug
    com.demo.security: debug



token:
  expiration_time: 43200000
  secret: secret_s