spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url:  jdbc:mariadb://localhost:3306/studyApi
    password: rnrdj123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      show_sql: true
