spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url:  jdbc:mariadb://localhost:3306/studyApi
    password: rnrdj123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      show_sql: true
  #############mail##########
  mail:
    host: smtp.gmail.com
    port: 587
    username: syseoz@gmail.com
    password: zmhklhpmtxzpcfiy
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
logging:
  level:
    com.demo.service: debug
    com.demo.security: debug



app:
  host: http://localhost:8080

token:
  expiration_time: 43200000
  secret: secret_s