server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    password: rnrdj123
    url: jdbc:postgresql://kafka.cq5azxcaeqze.ap-northeast-2.rds.amazonaws.com:5432/registration
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate: