server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springboot
    username: root
    password: rnrdj123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    com.example.springsecurity: debug
